block_labels = [ "DO NOT MERGE" ]

delete_merged_branches = true

status = [
    # "codecov/patch",
    # "codecov/project",
    "Travis CI - Branch",
    "VersionVigilante",
]

timeout_sec = 36000

[committer]
name = "BCBI Bot"
email = "bcbi-git@brown.edu"
